Import/mbedtls 3.4.0 take3
jenswi-linaro/optee_os pull request #12
Opened 2023-10-02 09:12 UTC by jenswi-linaro

Take3 is to use `mbedtls_rsa_deduce_primes()` and `mbedtls_rsa_deduce_crt()` to deduce eventual missing fields.

2023-10-02 11:10 UTC, larper2axis commented on ta/pkcs11/src/pkcs11_attributes.c
> +			      &key_pair_grp.G, NULL, NULL);
The f_rng parameter to mbedtls_ecp_mul  is mandatory in 3.4.

2023-10-02 11:20 UTC, larper2axis commented on ta/pkcs11/src/pkcs11_attributes.c
> +					  NULL, 0, NULL, 0);
Also here the f_rng parameter is mandatory for blinding.

2023-10-02 11:23 UTC, larper2axis requested changes
See my comments about missing f_rng parameters.

2023-10-02 12:51 UTC, jenswi-linaro commented
> See my comments about missing f_rng parameters.

Thanks, should be taken care of now.

2023-10-03 10:45 UTC, larper2axis commented on core/lib/libtomcrypt/mpi_desc.c
>  static int isprime(void *a, int b __unused, int *c)
Remove the __unused annotation

2023-10-03 11:08 UTC, larper2axis commented on lib/libutee/tee_api_arith_mpi.c
> +	rc = mbedtls_mpi_is_prime_ext(&mpi_op, MAX(confidenceLevel, 80U),
Remove the __unused annotation on the parameter confidenceLevel.

2023-10-03 12:32 UTC, larper2axis approved these changes

2023-10-03 12:53 UTC, jenswi-linaro commented
Comments addressed. @larper2axis do you want to add an Acked-by or Reviewed-by for some commits? OK if I squash in the updates?

2023-10-04 14:03 UTC, jforissier commented
- "libmbedtls: fix cipher_wrap.c for NIST AES Key Wrap mode"
  "libmedtls: core: update to mbedTLS 3.4.0 API"
  "core: ltc: configure internal SHA-1 and SHA-224"
  "core: ltc: configure internal MD5"
 
  `Acked-By: Jerome Forissier <jerome.forissier@linaro.org>`
 
- "ta: pkcs11: update to mbedTLS 3.4.0 API" + fixups:
  
  The mbedtls_pk_parse_key() has two new paramters with the new 3.x API
 
  s/paramters/parameters/
 
  `Acked-By: Jerome Forissier <jerome.forissier@linaro.org>`
  
- "core: LTC mpi_desc.c: update to mbedTLS 3.4.0 API" and "libutee: update to mbedTLS 3.4.0 API"

  The change to mbedtls_mpi_is_prime_ext() is not mentioned in the commit descriptions.
 
  `Acked-By: Jerome Forissier <jerome.forissier@linaro.org>`

- "libmedtls: core: update to mbedTLS 3.4.0 API"
 
  "The AES API has changed enough to prevent an efficient implementation of
  crypto_aes_enc_block() so switch the one provided via LTC is used
  instead."

  -> "so switch to the one provided via LTC instead"

  `Acked-By: Jerome Forissier <jerome.forissier@linaro.org>`

2023-10-04 14:04 UTC, jforissier commented
Should we be concerned with the CI errors? You've branched off of master haven't you, so I guess everything should build fine?

2023-10-05 07:55 UTC, jenswi-linaro commented
This one is needed also https://github.com/jenswi-linaro/optee_test/pull/1

2023-10-05 08:20 UTC, jenswi-linaro commented
Squashed and tags applied. Note that "libutee: update to mbedTLS 3.4.0 API" doesn't have any A-B or R-B tag yet.

2023-10-05 08:27 UTC, jforissier commented
> Squashed and tags applied. Note that "libutee: update to mbedTLS 3.4.0 API" doesn't have any A-B or R-B tag yet.

For that commit:

`Acked-by: Jerome Forissier <jerome.forissier@linaro.org>`

2023-10-05 08:39 UTC, jenswi-linaro commented
Tag applied. Are we happy with this? Should I push this branch to the new branch `import/mbedtls-3.4.0`? So I can create a new PR with a squash commit to be merged to master. Or should I wait a little longer?

2023-10-05 08:56 UTC, jforissier commented
> Tag applied. Are we happy with this? Should I push this branch to the new branch `import/mbedtls-3.4.0`? So I can create a new PR with a squash commit to be merged to master. Or should I wait a little longer?

I'd like to run a few tests from my release check list first if you don't mind. Hopefully by the end of the day.

2023-10-05 09:56 UTC, jenswi-linaro commented
Sure, no problem.

2023-10-05 16:10 UTC, jforissier commented
`Tested-by: Jerome Forissier <jerome.forissier@linaro.org> (vexpress-qemu_armv8a, mbedtls)`

For the record: I checked out a clean QEMUv8 environment and used the following command to build and run the tests:
`make -j check CFG_CRYPTOLIB_NAME=mbedtls CFG_CRYPTOLIB_DIR=lib/libmbedtls check XTEST_ARGS="-x pkcs11_1021 -x pkcs11_1022 -x pkcs11_1023"`

The failures in the PKCS#11 tests are a known issue with the previous MBedTLS already (https://github.com/OP-TEE/optee_os/issues/5418).

2023-10-06 14:38 UTC, merged

2023-10-06 14:57 UTC, jenswi-linaro commented
Pushed to https://github.com/OP-TEE/optee_os/tree/import/mbedtls-3.4.0